#!/bin/bash

set -e

FILE_NAME="${FILE_NAME:-01_initial_files}"
WORKSPACE_NAME="${WORKSPACE_NAME:-default}"
KONG_ADMIN="${KONG_ADMIN:-http://localhost:8001}"
UPSTREAM="$KONG_ADMIN/$WORKSPACE_NAME"

WORKSPACE_NAME=$WORKSPACE_NAME UPSTREAM=$UPSTREAM portal wipe $WORKSPACE_NAME 
WORKSPACE_NAME=$WORKSPACE_NAME UPSTREAM=$UPSTREAM portal deploy $WORKSPACE_NAME

curl "$UPSTREAM/files" -o "$FILE_NAME.json"

lua json_to_table.lua $FILE_NAME
