swagger: '2.0'
info:
  description: Developer Portal API
  title: Developer Portal Files API
  version: "1.0"
host: 127.0.0.1:8001
basePath: /
tags:
  - name: files
    description: List, edit, and delete Developer Portal Files.
schemes:
  - http
paths:
  /files:
    get:
      tags:
        - files
      summary: Get list of files
      description: ''
      operationId: getFiles
      parameters:
        - name: name
          type: string
          in: query
          description: File name
          required: false
        - name: content
          type: string
          in: query
          description: File contents
          required: false
        - name: type
          type: string
          in: query
          description: File type
          required: false
        - name: auth
          type: boolean
          in: query
          description: File is or is not authenticated
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/File'
  '/files/{name}':
    get:
      tags:
        - files
      summary: Get indiviual files
      description: ''
      operationId: getFile
      produces:
        - application/json
      parameters:
        - name: name
          type: string
          in: path
          description: File name.
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/File'
        '404':
          description: No file found by name or id
    patch:
      tags:
        - files
      summary: Edit files
      operationId: EditFile
      parameters:
        - name: name
          type: string
          in: path
          description: File name.
          required: true
        - name: name
          type: string
          in: query
          description: File name
          required: false
        - name: content
          type: string
          in: query
          description: File contents
          required: false
        - name: type
          type: string
          in: query
          description: File type
          required: false
        - name: auth
          type: boolean
          in: query
          description: File is or is not authenticated
          required: false
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/File'
        '404':
          description: No file found by name or id
    delete:
      tags:
        - files
      summary: Delete files
      operationId: DeleteFile
      description: ''
      parameters:
        - name: name
          type: string
          in: path
          description: File name.
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/File'
        '404':
          description: No file found by name or id
  '/files/unauthenticated':
    get:
      tags:
        - files
      summary: Unauthenticated files
      description: ''
      operationId: GetUnauthenticatedFiles
      produces:
        - application/json
      parameters:
        - name: name
          type: string
          in: path
          description: File name.
          required: true
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/File'
        '404':
          description: No file found by name or id

definitions:
  File:
    type: object
    example:
      name: 'petstore'
      type: 'spec'
      auth: true
      contents: "<h1>Hello {{name}}<h1>"
    properties:
      name:
        type: string
      type:
        type: string
      auth:
        type: boolean
      contents:
        type: string
