openapi: 3.0.0
info:
  description: Send mail via API Rest
  version: 1.4.0-rc
  title: SMTP Client API Rest
servers:
- url: https://api-manager.dev.universia.net:8443/coreplatform-smtp-client/api
- url: http://localhost:3002/api
paths:
  /sendMail:
    post:
      summary: Send a email
      operationId: sendMail
      tags:
      - mail
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MailData'
      responses:
        200:
          description: Mail send successfully
        400:
          description: Bad Request
        500:
          description: Server Error
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    MailData:
      type: object
      required:
      - from
      - to
      properties:
        from:
          type: string
        to:
          type: array
          items:
            type: string
        cc:
          type: array
          items:
            type: string
        bcc:
          type: array
          items:
            type: string
        subject:
          type: string
        text:
          type: string
        html:
          type: string
        attachments:
          type: array
          items:
            $ref: '#/components/schemas/Attachment'
    Attachment:
      type: object
      properties:
        filename:
          type: string
        content:
          type: string
        contentType:
          type: string
        encoding:
          type: string
      xml:
        name: MailData
    Error:
      required:
      - code
      - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
