name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

env:
  DOCKER_REGISTRY_USR: ${{ secrets.GHA_DOCKERHUB_PULL_USER }}
  DOCKER_REGISTRY_PSW: ${{ secrets.GHA_KONG_ORG_DOCKERHUB_PUBLIC_TOKEN }}

jobs:
  build:
    timeout-minutes: ${{ fromJSON(vars.GHA_DEFAULT_TIMEOUT) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: checkout kong portal tools
        uses: actions/checkout@v3
        with:
          repository: Kong/kong-portal-tools
          path: kong-portal-tools
          token: ${{ secrets.GHA_KONG_BOT_READ_TOKEN }}

      - run: echo "COMPOSE_PROJECT_NAME=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: copy kong-portal-tools/kong-portal-ci to current dir
        run: |
          cp -a kong-portal-tools/kong-portal-ci/. .

      - name: Make build
        run: |
          make build

      - name: Make run-e2e-kong-oauth
        run: |
          make run-e2e-kong-oauth

      - name: Make run-e2e-external-oauth
        run: |
          make run-e2e-external-oauth

      - name: Make create-portal-files
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        run: |
          make create-portal-files
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_KONG_PORTAL_TOKEN }}
